# Usa una imagen base con Java 17 (cámbiala según tu versión)
FROM eclipse-temurin:17-jdk-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el JAR generado en el contenedor
COPY target/*.jar app.jar

# Expone el puerto en el que corre tu aplicación (cámbialo si usas otro)
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
